### ISSUE TITLE
Strapi V4

### ISSUE THREAD

**Issue by Jbmanllr** [Deathwish98/medusa-plugin-strapi#1]
Hello ! Any plan to upgrade it for Strapi V4?

**Comment by SharmaPawan11** [comment]
I was planning to do it as well. Will update the progress once I start to work on it.

**Comment by juicecultus** [comment]
Is this error v4 related?
```
npx create-strapi-app strapi-medusa --template https://github.com/Deathwish98/strapi-medusa-template.git
Need to install the following packages:
  create-strapi-app
Ok to proceed? (y) y
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
? Choose your installation type Quickstart (recommended)
Creating a quickstart project.
Creating a new Strapi application at /Users/juice/code/strapi-medusa.
Creating files.
Error: ⛔️ Template installation failed: Command failed: /bin/sh -c npm view https://github.com/Deathwish98/strapi-medusa-template.git name version --silent


    at createProject (/Users/juice/.npm/_npx/f5b733dbc92df62b/node_modules/@strapi/generate-new/lib/create-project.js:82:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createQuickStartProject (/Users/juice/.npm/_npx/f5b733dbc92df62b/node_modules/@strapi/generate-new/lib/create-quickstart-project.js:23:3)
```

**Comment by SharmaPawan11** [comment]
> Is this error v4 related?
> 
> ```
> npx create-strapi-app strapi-medusa --template https://github.com/Deathwish98/strapi-medusa-template.git
> Need to install the following packages:
>   create-strapi-app
> Ok to proceed? (y) y
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> ? Choose your installation type Quickstart (recommended)
> Creating a quickstart project.
> Creating a new Strapi application at /Users/juice/code/strapi-medusa.
> Creating files.
> Error: ⛔️ Template installation failed: Command failed: /bin/sh -c npm view https://github.com/Deathwish98/strapi-medusa-template.git name version --silent
> 
> 
>     at createProject (/Users/juice/.npm/_npx/f5b733dbc92df62b/node_modules/@strapi/generate-new/lib/create-project.js:82:15)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async createQuickStartProject (/Users/juice/.npm/_npx/f5b733dbc92df62b/node_modules/@strapi/generate-new/lib/create-quickstart-project.js:23:3)
> ```

Yes, It was working before the release of Strapi v4. 
Until I update this plugin for Strapi v4, we gotta use `create-strapi-app@3.6.8` for it to work.
Thanks for pointing it out.
Updating it in README as well.

**Comment by lithiumlab** [comment]
I would love to help on the upgrade to v4. All tutorials about strapi / medusa integration out there are failing because of this. I find very interesting to mix up medusa with strapi letting strapi extend things that are not directly commerce related.

**Comment by MattiaEffendi** [comment]
Hi! Have you got any updates on this? The template seems to not work even if you try to create a Strapi 3 project, so if you are starting from fresh right now it's not possible to create any Strapi project, neither in version 3 or 4 😢 

If you have a workaround let me know and i will be more than happy to try it out!

Thanks for your work!
