### ISSUE TITLE
ApplicationError: The type is required

### ISSUE THREAD

**Issue by fendyk** [Deathwish98/medusa-plugin-strapi#10]
When running:
`npx create-strapi-app strapi-medusa --template shahednasser/strapi-medusa-template`

I get:
```
ApplicationError: The type is required
    at getFieldSize (/Users/raulfernandez/IdeaProjects/strapi-medusa/node_modules/@strapi/plugin-content-manager/server/services/field-sizes.js:61:15)
    at getDefaultFieldSize (/Users/raulfernandez/IdeaProjects/strapi-medusa/node_modules/@strapi/plugin-content-manager/server/services/utils/configuration/layouts.js:27:10)
    at appendToEditLayout (/Users/raulfernandez/IdeaProjects/strapi-medusa/node_modules/@strapi/plugin-content-manager/server/services/utils/configuration/layouts.js:140:27)
    at createDefaultEditLayout (/Users/raulfernandez/IdeaProjects/strapi-medusa/node_modules/@strapi/plugin-content-manager/server/services/utils/configuration/layouts.js:50:10)
    at createDefaultLayouts (/Users/raulfernandez/IdeaProjects/strapi-medusa/node_modules/@strapi/plugin-content-manager/server/services/utils/configuration/layouts.js:34:11)
    at createDefaultConfiguration (/Users/raulfernandez/IdeaProjects/strapi-medusa/node_modules/@strapi/plugin-content-manager/server/services/utils/configuration/index.js:26:20)
    at async generateNewConfiguration (/Users/raulfernandez/IdeaProjects/strapi-medusa/node_modules/@strapi/plugin-content-manager/server/services/configuration.js:54:36)
    at async Promise.all (index 13)
    at async Object.syncConfigurations (/Users/raulfernandez/IdeaProjects/strapi-medusa/node_modules/@strapi/plugin-content-manager/server/services/configuration.js:68:5)
    at async Object.module.exports [as bootstrap] (/Users/raulfernandez/IdeaProjects/strapi-medusa/node_modules/@strapi/plugin-content-manager/server/bootstrap.js:13:3) {
  details: {}
}

```

**Comment by samhenderson511** [comment]
I had this issue as well, got around it by using the default app and copying the template files into it

**Comment by earmellin** [comment]
I have the same issue, there is something wrong in initial configuration flow.
@samhenderson511 can you explain better how you avoided the problem? what do you mean with "default app"?

**Comment by samhenderson511** [comment]
I actually couldn't get it to sync with Medusa in the end anyway but I installed the default strapi starter and then copied the template files across

**Comment by earmellin** [comment]
@samhenderson511 but so if in the end it doesn't work I don't think it's worth installing it...

**Comment by ruskoloma** [comment]
The same problem.
Maybe somebody in the issue have tried plugin for contentful cms? Does it work?

**Comment by samhenderson511** [comment]
I haven't tried it but you need to install a whole new starter project for it which I didn't want to do
